name: 'Blacklist Job'

on:

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  run_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Run Python script
      run: python blacklist/blacklist.py
      
    - name: Upload generated files
      uses: actions/upload-artifact@v4
      with:
        name: generated-files
        path: |
          blacklist/blacklist_auto.txt
          blacklist/whitelist_auto.txt
          blacklist/whitelist_auto_tv.txt
          
    - name: Commit changes
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add blacklist/
          git commit -m ":tada:  AutoUpdate Blacklist $(date +'%Y%m%d')"

          current_datetime=$(date +"%Y%m%d_%H%M%S")
          cp blacklist/blacklist_auto.txt history/blacklist/"${current_datetime}_blacklist_auto.txt"
          cp blacklist/whitelist_auto.txt history/blacklist/"${current_datetime}_whitelist_auto.txt"
          cp blacklist/whitelist_auto_tv.txt history/blacklist/"${current_datetime}_whitelist_auto_tv.txt"
          git add history/blacklist/"${current_datetime}_blacklist_auto.txt"
          git add history/blacklist/"${current_datetime}_whitelist_auto.txt"
          git add history/blacklist/"${current_datetime}_whitelist_auto_tv.txt"
          git commit -m "Archive blacklist file with timestamp"
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
        
